
name: Deploy Azi

on:

  push:
    branches: [ "master" ]

  workflow_dispatch:


jobs:
  build_frontend_docker_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/metalan_frontend:latest
  deploy:
 
    name: Deploy Azi
    runs-on: ubuntu-latest
    needs:
      - build_frontend_docker_and_push
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST_URL }}
          username: ${{ secrets.HOST_LOGIN }}
          password: ${{ secrets.HOST_PASSWORD }}
          script_stop: true
          command_timeout: 15m
          script: |
            cd /root/azi
            git pull
            docker-compose down --remove-orphans
            docker-compose -f docker-compose.yml up -d --build
            docker rmi $(docker images -f 'dangling=true' -q) || true
