
name: Deploy Azi

on:

  push:
    branches: [ "master" ]

  workflow_dispatch:


jobs:
  deploy:
 
    name: Deploy Metalan
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST_URL }}
          username: ${{ secrets.HOST_LOGIN }}
          password: ${{ secrets.HOST_PASSWORD }}
          script_stop: true
          command_timeout: 15m
          script: |
            cd /root/azi
            git pull
            docker-compose down --remove-orphans
            docker-compose -f docker-compose.yml up -d --build
            docker rmi $(docker images -f 'dangling=true' -q) || true
